version: "3.3"
services:
  mysql:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQ_USER: sato
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"

    ports:
     - 3232:3306

    volumes:
     - ./db/mysql_data:/var/lib/mysql

  php:
    build: ./php
    ports: 
     - 8282:80
    volumes:
     - ./php/html:/var/www/html
    depends_on:
     - mysql
